// Deploy as an Apps Script web app, executing as the sheet owner.
// All calls must come through the serverless API with its private shared secret.
function doPost(e){try{if(!e.postData||e.postData.contents.length>40000)throw Error('Invalid request.');const b=JSON.parse(e.postData.contents);const secret=PropertiesService.getScriptProperties().getProperty('API_SECRET');if(!secret||typeof b.secret!=='string'||!constantEqual(secret,b.secret))throw Error('Unauthorized.');const data=dispatch(b);return json({ok:true,data:data});}catch(e){return json({ok:false,error:e.message||'Unable to process request.'});}}
function json(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
function constantEqual(a,b){const x=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,a),y=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,b);let result=0;for(let i=0;i<x.length;i++)result|=x[i]^y[i];return result===0;}
function book(){const id=PropertiesService.getScriptProperties().getProperty('SHEET_ID');if(!id)throw Error('Storage is not configured.');return SpreadsheetApp.openById(id);}
function headers(schema){return ['ID','Submission Date','Submission Time',...schema.fields.map(f=>f.key),'Consent','Status','Admin Notes','Updated By','Updated At'];}
function sheet(tab){const allowed=Object.values(SCHEMAS).some(s=>s.tab===tab)||tab==='Impact_Statistics';if(!allowed)throw Error('Unknown sheet.');const sh=book().getSheetByName(tab);if(!sh)throw Error('Run setupSheets before accepting submissions.');return sh;}
function records(tab){const sh=sheet(tab),data=sh.getDataRange().getDisplayValues();const columns=data.shift();return {tab:tab,columns:columns,rows:data.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(columns.map((c,i)=>[c,r[i]])))};}
function setupSheets(){const ss=book();Object.values(SCHEMAS).forEach(s=>{let sh=ss.getSheetByName(s.tab);if(!sh)sh=ss.insertSheet(s.tab);if(!sh.getLastRow()){const h=headers(s);sh.getRange(1,1,1,h.length).setValues([h]).setFontWeight('bold').setBackground('#154d43').setFontColor('#ffffff');sh.setFrozenRows(1);sh.getRange(2,1,Math.max(1,sh.getMaxRows()-1),h.length).setNumberFormat('@');}});let impact=ss.getSheetByName('Impact_Statistics');if(!impact)impact=ss.insertSheet('Impact_Statistics');if(!impact.getLastRow()){impact.appendRow(['ID','Label','Value','Published','Updated By','Updated At']);['Blood Donors Registered','Patients Supported','Hair Donations','Medicine Requests Supported','Student Volunteers','Requests Completed'].forEach((label,i)=>impact.appendRow(['impact-'+i,label,0,'FALSE','','']));impact.setFrozenRows(1);}}
function dispatch(b){
 if(b.action==='impact')return records('Impact_Statistics').rows.filter(r=>r.Published==='TRUE'&&/^\d+$/.test(r.Value)).map(r=>({Label:r.Label,Value:Number(r.Value)}));
 if(b.action==='donors'){const f=b.filters||{};return records('Blood_Donors').rows.filter(r=>r.Status==='Active'&&String(r.Consent).toLowerCase()==='true'&&(!f.bloodGroup||r['Blood Group']===f.bloodGroup)&&(!f.district||r.District.toLowerCase().includes(f.district.toLowerCase()))&&(!f.city||r.City.toLowerCase().includes(f.city.toLowerCase()))&&(!f.availability||r.Availability===f.availability)).slice(0,100).map(publicDonor);}
 if(b.action==='records')return records(b.tab);
 if(b.action==='exportAll')return [...Object.values(SCHEMAS).map(s=>records(s.tab)),records('Impact_Statistics')];
 if(b.action==='summary'){const data={};Object.values(SCHEMAS).forEach(s=>data[s.tab]=records(s.tab).rows);return [{label:'Total Blood Donors',value:data.Blood_Donors.length},{label:'Available Blood Donors',value:data.Blood_Donors.filter(r=>r.Status==='Active'&&r.Availability==='Available').length},{label:'Pending Blood Requests',value:data.Blood_Requests.filter(r=>r.Status==='Pending').length},{label:'Hair Donations',value:data.Hair_Donors.filter(r=>r.Status==='Completed').length},{label:'Wig Requests',value:data.Wig_Requests.length},{label:'Medicine Requests',value:data.Medicine_Requests.length},{label:'Birthday Pledges',value:data.Birthday_Pledges.length},{label:'Volunteers',value:data.Volunteers.length},{label:'Unresolved Contact Messages',value:data.Contact_Messages.filter(r=>!['Completed','Rejected'].includes(r.Status)).length}];}
 const lock=LockService.getScriptLock();if(!lock.tryLock(20000))throw Error('The service is busy. Please retry.');try{
 if(b.action==='submit'){
 const schema=SCHEMAS[b.kind],values=validateSubmission(schema,b.values),sh=sheet(schema.tab);const data=records(schema.tab);if(data.rows.some(r=>r.ID===b.requestId))return {id:b.requestId,duplicate:true};
 const networkCache=CacheService.getScriptCache();if(b.rateKey){const nk='network-'+b.rateKey;const hits=Number(networkCache.get(nk)||0);if(hits>=5)throw Error('Too many submissions. Please wait a minute.');networkCache.put(nk,String(hits+1),60);}
 const identity=String(values.Phone||values.Email||'').replace(/[^a-zA-Z0-9]/g,'').toLowerCase();const key='rate-'+Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,b.kind+identity));const cache=CacheService.getScriptCache();if(cache.get(key))throw Error('Please wait a minute before making another submission.');
 const now=new Date();const date=Utilities.formatDate(now,'Asia/Kolkata','yyyy-MM-dd'),time=Utilities.formatDate(now,'Asia/Kolkata','HH:mm:ss');
 const row=Object.assign({},values,{ID:b.requestId,'Submission Date':date,'Submission Time':time,Status:schema.status,'Admin Notes':''});
 if(data.rows.some(r=>r['Submission Date']===date&&schema.fields.every(f=>String(r[f.key]).toLowerCase()===String(values[f.key]).toLowerCase())))throw Error('These details have already been submitted today. Please contact the team to make changes.');
 sh.appendRow(data.columns.map(c=>row[c]===undefined?'':typeof row[c]==='boolean'?row[c]:safeCell(row[c])));SpreadsheetApp.flush();cache.put(key,'1',60);return {id:b.requestId};
 }
 if(b.action==='update'){const changes=validateUpdate(b.tab,b.changes),sh=sheet(b.tab),data=records(b.tab);const match=data.rows.findIndex(r=>r.ID===b.id);if(match<0)throw Error('Record not found.');const ids=sh.getRange(2,data.columns.indexOf('ID')+1,Math.max(1,sh.getLastRow()-1),1).getDisplayValues();const rowIndex=ids.findIndex(r=>r[0]===b.id)+2;if(rowIndex<2)throw Error('Record not found.');changes['Updated By']=safeCell(b.admin);changes['Updated At']=new Date().toISOString();Object.keys(changes).forEach(key=>{const col=data.columns.indexOf(key);if(col>=0)sh.getRange(rowIndex,col+1).setValue(changes[key]);});SpreadsheetApp.flush();return {saved:true};}
 throw Error('Unknown operation.');
 }finally{lock.releaseLock();}
}
