import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {validateSubmission,publicDonor,safeCell,validateUpdate} from '../backend/validation.mjs';
const schemas=JSON.parse(readFileSync(new URL('../backend/schemas.json',import.meta.url)));
function sample(schema){return Object.fromEntries([...schema.fields.map(f=>[f.key,f.type==='select'?f.options[0]:f.type==='email'?'test@example.org':f.type==='tel'?'+91 9876543210':f.type==='date'?'2026-10-10':f.type==='number'?25:f.type==='checkbox'?false:'Example']),['Consent',true]])}
test('all eight forms validate and preserve supplied fields',()=>{assert.equal(Object.keys(schemas).length,8);for(const schema of Object.values(schemas)){const r=validateSubmission(schema,sample(schema));for(const f of schema.fields)assert.ok(f.key in r);assert.equal(r.Consent,true)}});
test('missing consent and honeypots fail',()=>{const s=schemas['blood-donor'];assert.throws(()=>validateSubmission(s,{...sample(s),Consent:false}),/Consent/);assert.throws(()=>validateSubmission(s,{...sample(s),website:'spam'}),/rejected/)});
test('invalid enums, dates, phones, units and oversized text fail',()=>{const s=schemas['blood-request'];for(const patch of [{'Blood Group':'X+'},{Phone:'123'},{Units:-2},{Units:1.5},{'Required Date':'2026-02-31'},{'Additional Message':'x'.repeat(3001)}])assert.throws(()=>validateSubmission(s,{...sample(s),...patch}))});
test('email contact preference needs email',()=>{const s=schemas['blood-donor'];assert.throws(()=>validateSubmission(s,{...sample(s),'Preferred Contact':'Email',Email:''}),/email/)});
test('untrusted extra fields cannot set status or admin notes',()=>{const s=schemas['contact'];const v=validateSubmission(s,{...sample(s),Status:'Approved','Admin Notes':'override'});assert.equal(v.Status,undefined);assert.equal(v['Admin Notes'],undefined)});
test('formula-like values are escaped only at storage/export boundary',()=>{for(const s of ['=IMPORTXML("url")','+1+2','-5+4','@SUM(A1)','  =1'])assert.ok(safeCell(s).startsWith("'"));assert.equal(validateSubmission(schemas['contact'],sample(schemas['contact'])).Phone,'+91 9876543210')});
test('public donor output is an explicit safe allowlist',()=>{const d=publicDonor({Name:'Rahul Menon',Phone:'9876543210',Email:'secret@example.org',Address:'private',District:'Thrissur',City:'Thrissur','Blood Group':'O+',Availability:'Available','Admin Notes':'private'});assert.deepEqual(d,{name:'Rahul',bloodGroup:'O+',city:'Thrissur',availability:'Available'});assert.equal(JSON.stringify(d).includes('9876543210'),false)});
test('admin mutations reject unexpected statuses and negative impact',()=>{assert.throws(()=>validateUpdate('Blood_Donors',{Status:'hacked','Admin Notes':''}));assert.throws(()=>validateUpdate('Impact_Statistics',{Value:-1}));assert.deepEqual(validateUpdate('Impact_Statistics',{Value:42,Published:true}),{Value:42,Published:'TRUE'})});
function harness(){const tables=new Map();const props={SHEET_ID:'test',API_SECRET:'private-key'};const cache=new Map();function sheet(name){const rows=[];return {rows,getDataRange:()=>({getDisplayValues:()=>rows.map(r=>r.map(v=>String(v)))}),getLastRow:()=>rows.length,getMaxRows:()=>1000,setFrozenRows(){},appendRow(r){rows.push(r)},getRange(row,col,n=1,m=1){const range={setValues(values){values.forEach((r,i)=>{rows[row-1+i]??=[];r.forEach((v,j)=>rows[row-1+i][col-1+j]=v)});return range},setValue(value){rows[row-1][col-1]=value;return range},getDisplayValues(){return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>String(rows[row-1+i]?.[col-1+j]??'')))},setFontWeight(){return range},setBackground(){return range},setFontColor(){return range},setNumberFormat(){return range}};return range}}}const book={getSheetByName:n=>tables.get(n),insertSheet(n){const s=sheet(n);tables.set(n,s);return s}};let locked=false;const c={console,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},SpreadsheetApp:{openById:()=>book,flush(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},Utilities:{DigestAlgorithm:{SHA_256:1},computeDigest:(_,s)=>Array.from(Buffer.from(s)),base64EncodeWebSafe:s=>Buffer.from(s).toString('base64'),formatDate:(_,__,fmt)=>fmt==='yyyy-MM-dd'?'2026-09-09':'12:00:00'},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})},LockService:{getScriptLock:()=>({tryLock(){locked=true;return true},releaseLock(){locked=false}})}};vm.createContext(c);vm.runInContext(readFileSync(new URL('../backend/Code.gs',import.meta.url),'utf8'),c);c.setupSheets();return {c,tables,cache,locked:()=>locked}}
test('Apps Script rejects unauthenticated calls',()=>{const {c}=harness();const r=c.doPost({postData:{contents:JSON.stringify({action:'exportAll',secret:'bad'})}});assert.equal(r.ok,false);assert.match(r.error,/Unauthorized/)});
test('submission retry returns same reference without duplicate row; rate limiting blocks a new reference',()=>{const h=harness();const request={action:'submit',kind:'contact',values:sample(schemas.contact),requestId:'c0897e26-93db-4a2e-bcb4-68777e1936df'};const one=h.c.dispatch(request);const two=h.c.dispatch(request);assert.equal(one.id,two.id);assert.equal(two.duplicate,true);assert.equal(h.tables.get('Contact_Messages').rows.length,2);assert.equal(h.locked(),false);assert.throws(()=>h.c.dispatch({...request,requestId:'different'}),/wait a minute/)});
test('records are saved with default status and server date, and edits reach the sheet',()=>{const {c,tables}=harness();c.dispatch({action:'submit',kind:'contact',values:sample(schemas.contact),requestId:'test-id'});c.dispatch({action:'update',tab:'Contact_Messages',id:'test-id',changes:{Status:'Completed','Admin Notes':'Reviewed'},admin:'admin@example.org'});const result=c.dispatch({action:'records',tab:'Contact_Messages'});assert.equal(result.rows[0].Status,'Completed');assert.equal(result.rows[0]['Submission Date'],'2026-09-09');assert.equal(result.rows[0]['Updated By'],'admin@example.org');assert.ok(tables.size===9)});
test('unpublished impact does not leak and a published update appears',()=>{const {c}=harness();assert.equal(c.dispatch({action:'impact'}).length,0);c.dispatch({action:'update',tab:'Impact_Statistics',id:'impact-0',changes:{Value:12,Published:true},admin:'admin'});assert.equal(c.dispatch({action:'impact'})[0].Value,12)});
