import { Injectable } from '@angular/core';
import { from, Observable } from 'rxjs';
export interface Config{authMode?:string;spamMode?:string;apiUrl:string;googleClientId:string;turnstileSiteKey:string;contactEmail:string;contactPhone:string;instagramUrl:string;facebookUrl:string;whatsappUrl:string;sheetUrl:string}
@Injectable({providedIn:'root'})export class Api{
 token='';config:Config|null=null;
 async settings(){if(!this.config){const r=await fetch('/config.json');if(!r.ok)throw Error('Unable to load configuration. Please refresh.');this.config=await r.json()}return this.config!}
 async call(action:string,data:Record<string,unknown>={}){const c=await this.settings();if(!c.apiUrl)throw Error('Online submissions are not open yet. Please check back when the volunteer team launches this service.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(c.apiUrl,{method:'POST',body:JSON.stringify({action,...data,token:this.token}),headers:{'Content-Type':'text/plain;charset=utf-8'},signal:controller.signal,redirect:'follow',credentials:'same-origin'});const json=await r.json().catch(()=>({ok:false,error:'We could not reach the volunteer team. Please try again.'}));if(!r.ok||!json.ok)throw Error(json.error||'Something went wrong. Please try again.');return json.data;}catch(e){if(e instanceof DOMException&&e.name==='AbortError')throw Error('The request timed out. Retry to safely check your submission.');throw e}finally{clearTimeout(timer)}}
 request(action:string,data:Record<string,unknown>={}):Observable<any>{return from(this.call(action,data))}
}
export function loadScript(src:string):Promise<void>{return new Promise((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[data-src="'+src+'"]');if(existing?.dataset['loaded']){resolve();return}if(existing){existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(Error('Could not load verification. Refresh to retry.')),{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.dataset['src']=src;s.onload=()=>{s.dataset['loaded']='true';resolve()};s.onerror=()=>{s.remove();reject(Error('Could not load verification. Please check your connection.'))};document.head.appendChild(s)})}
