import { Component, inject } from '@angular/core';
import { RouterOutlet, RouterLink, Router, NavigationEnd } from '@angular/router';
import { Title, Meta } from '@angular/platform-browser';
@Component({selector:'app-root',standalone:true,imports:[RouterOutlet,RouterLink],template:`
<a class="skip" href="#main">Skip to content</a>
<div class="topline">STUDENT-LED. COMMUNITY-POWERED. <span>From GMC Thrissur, with care ♡</span></div>
<header><a routerLink="/" class="brand" (click)="menu=false"><img class="brand-logo" src="/logo.png" alt="Punarjani — The Pratheeksha Reborn" width="64" height="64"><span>Punarjani<small>CHARITY WING OF THRISSUR MEDICOS</small></span></a>
<button class="menu-button" (click)="menu=!menu" [attr.aria-expanded]="menu" aria-label="Toggle navigation">☰</button>
<nav [class.open]="menu" (click)="menu=false"><a routerLink="/">Home</a><a routerLink="/" fragment="wings">Our Wings</a><a routerLink="/impact">Impact</a><a routerLink="/about">About</a><a routerLink="/our-people">Our People</a><a routerLink="/contact">Contact</a><a routerLink="/volunteer" class="button small">Join the Cause <span>↗</span></a></nav></header>
<main id="main"><router-outlet/></main>
<footer><div class="footer-top"><a routerLink="/" class="brand"><img class="brand-logo" src="/logo.png" alt="Punarjani logo" width="64" height="64"><span>Punarjani<small>THE PRATHEEKSHA REBORN</small></span></a><p>Compassion has a place here.<br>So do you.</p><a routerLink="/volunteer" class="button light">Find your way to give ↗</a></div><div class="footer-links"><span>GMC Thrissur · Kerala, India</span><a routerLink="/about">About</a><a routerLink="/contact">Contact & social channels</a><a routerLink="/privacy">Privacy Policy</a><a routerLink="/terms">Terms</a><a routerLink="/admin">Admin</a></div><div class="footer-bottom"><span>Built with ❤️ for humanity.</span><span>A student-powered healthcare support network.</span></div></footer>`})
export class App{menu=false;router=inject(Router);title=inject(Title);meta=inject(Meta);constructor(){this.router.routeReuseStrategy.shouldReuseRoute=()=>false;this.router.events.subscribe(e=>{if(e instanceof NavigationEnd){this.menu=false;const part=e.urlAfterRedirects.split(/[?#]/)[0].split('/').filter(Boolean).pop()||'Home';this.title.setTitle(part.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())+' · GMC Charity Wing');let link=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=location.origin+e.urlAfterRedirects.split(/[?#]/)[0];}})}}
