import {Component,inject,OnInit} from '@angular/core';
import {Api} from './api';
import {RouterLink} from '@angular/router';
@Component({standalone:true,imports:[RouterLink],template:`
<section class="hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="live-dot"></span> THE CHARITY WING OF GMC THRISSUR</div><h1>Small Acts.<br>Extraordinary<br><em>Impact.</em><span class="spark">✳</span></h1><p>A student-led initiative from GMC Thrissur connecting compassion, healthcare and people who want to make a difference.</p><div class="actions"><a routerLink="/volunteer" class="button">Get Involved <span>↗</span></a><a href="#wings" class="text-link">Explore Our Wings <span>↓</span></a></div><div class="hero-proof"><div class="mini-symbols"><span>♡</span><span>✚</span><span>✳</span></div><div><strong>Students at heart. Humanity in action.</strong><small>One community. Countless ways to care.</small></div></div></div>
<div class="hero-visual"><div class="photo-frame"><img src="/community.webp" alt="Illustration of medical student volunteers together on a Kerala campus" width="900" height="1050" fetchpriority="high"><div class="photo-label"><span class="live-dot"></span> COMPASSION, IN ACTION</div><div class="photo-quote">A little of your time.<br>A world of difference.</div><small class="image-disclosure">Conceptual imagery</small></div><div class="float-card"><span class="float-icon">♡</span><div>Care that connects.<small>People helping people.</small></div><span class="tiny-star">✦</span></div><div class="round-stamp">GIVE · CONNECT · CARE<br><span>↗</span><br>HEAL · HOPE</div><div class="hero-flow" aria-label="From donor to student volunteers to patient to impact"><span>Donor</span><b>→</b><span>Student volunteers</span><b>→</b><span>Patient</span><b>→</b><span>Impact</span></div></div></section>
<div class="belief-strip"><span>Rooted in healthcare.</span><b>Driven by compassion.</b><span>Powered by students.</span><span class="strip-star">✳</span></div>
<section class="wrap home-impact"><div class="eyebrow">EVERY ACT MATTERS</div><div class="impact-row">@for(stat of stats;track stat.Label){<div><strong>{{stat.display}}</strong><span>{{stat.Label}}</span></div>}</div><p class="hint">{{verified ? "Verified figures from our charity team." : "Impact figures will be shared after verification by the team."}} <a routerLink="/impact">Explore our impact ↗</a></p></section><section class="section wrap" id="wings"><div class="section-heading"><div><div class="eyebrow">FOUR WINGS. ONE PURPOSE.</div><h2>Find your way<br>to make a difference.</h2></div><p>Every act of giving has a ripple effect.<br>Choose a cause that speaks to you.</p></div><div class="wing-grid">
<a class="wing-card blood" routerLink="/wings/blood"><div class="card-top"><span class="wing-icon"><svg width="30" height="34" viewBox="0 0 24 28" fill="none" aria-hidden="true"><path d="M12 2S3 12 3 18a9 9 0 0 0 18 0C21 12 12 2 12 2Z" stroke="currentColor" stroke-width="1.6"/><path d="M7 18a5 5 0 0 0 5 5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></span><span>01 /</span></div><h3>Blood Wing</h3><p>A connection today.<br>Someone’s tomorrow.</p><div class="card-bottom">Give the gift of life <span>↗</span></div></a>
<a class="wing-card hair" routerLink="/wings/hair"><div class="card-top"><span class="wing-icon">≈</span><span>02 /</span></div><h3>Hair to Care</h3><p>A part of you.<br>A new confidence for someone.</p><div class="card-bottom">Share a little hope <span>↗</span></div></a>
<a class="wing-card medicine" routerLink="/wings/medicine"><div class="card-top"><span class="wing-icon">✚</span><span>03 /</span></div><h3>Drug Wing</h3><p>Essential medicines.<br>One less worry.</p><div class="card-bottom">Make care possible <span>↗</span></div></a>
<a class="wing-card birthday" routerLink="/wings/birthday"><div class="card-top"><span class="wing-icon">✳</span><span>04 /</span></div><h3>Gift of Giving</h3><p>Your special day.<br>Someone else’s reason to smile.</p><div class="card-bottom">Pledge your birthday <span>↗</span></div></a></div></section>
<section class="journey-section"><div class="wrap"><div class="eyebrow">A SIMPLE ACT. A SHARED JOURNEY.</div><h2>Good begins with you.</h2><div class="journey"><div><span>01</span><h3>You reach out</h3><p>Register to give or request support.</p></div><b>⟶</b><div><span>02</span><h3>Students connect</h3><p>Our volunteers coordinate with care.</p></div><b>⟶</b><div><span>03</span><h3>Someone finds hope</h3><p>Together, we help care reach people.</p></div></div></div></section>
<section class="section wrap story-tease"><div><div class="eyebrow">THE PEOPLE BEHIND THE PURPOSE</div><h2>Learning medicine.<br>Practising humanity.</h2></div><div><p>We are students of GMC Thrissur, brought together by a simple belief: compassionate people can make healthcare support more accessible.</p><a routerLink="/our-people" class="text-link">Meet our advisors & team ↗</a><a routerLink="/impact" class="text-link spaced">Explore our impact ↗</a></div></section>
`})export class Home implements OnInit{api=inject(Api);verified=false;stats:any[]=['Blood Donors Registered','Patients Supported','Hair Donations','Medicine Requests Supported','Student Volunteers','Requests Completed'].map(Label=>({Label,display:'—'}));async ngOnInit(){try{const c=await this.api.settings();if(!c.apiUrl)return;const data=await this.api.call('impact');if(!data.length)return;this.verified=true;this.stats=data.map((s:any)=>({...s,display:s.Value}));if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){const start=performance.now();const tick=(now:number)=>{const t=Math.min(1,(now-start)/1100);this.stats.forEach(s=>s.display=Math.round(s.Value*t));if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);observer.disconnect()}});const el=document.querySelector('.home-impact');if(el)observer.observe(el)}}catch{}}}
