import {Component,inject} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {Api} from './api';
import {BLOOD_GROUPS} from './schemas';
const WINGS:Record<string,any>={blood:{title:'Blood Wing',headline:'Your Blood Can Be Someone’s Tomorrow.',description:'Connect with people who need blood through a student-powered network of voluntary donors.',primary:'Register as Blood Donor',form:'blood-donor',secondary:'Request Blood',second:'blood-request',symbol:'♡'},hair:{title:'Hair to Care',headline:'Donate Hair. Restore Confidence.',description:'Help support hair collection and wig creation for people undergoing cancer treatment.',primary:'Donate Hair',form:'hair-donor',secondary:'Request a Wig',second:'wig-request',symbol:'≈'},medicine:{title:'Drug Wing',headline:'Healthcare Should Never Be Out of Reach.',description:'Helping patients who cannot afford necessary medicines find a path to support.',primary:'Request Medicine Assistance',form:'medicine-request',secondary:'View Impact',symbol:'✚'},birthday:{title:'Gift of Giving',headline:'Make Your Birthday Someone Else’s Reason to Smile.',description:'Celebrate your day by expressing an interest in helping others. Our volunteers will help you explore ways to contribute.',primary:'Birthday Giving Pledge',form:'birthday-pledge',secondary:'View Impact',symbol:'✳'}};
@Component({standalone:true,imports:[RouterLink,FormsModule],template:`
@if(wing){<section [class]="key"><div class="wrap page-hero"><a routerLink="/" fragment="wings" class="breadcrumb">Our wings / {{wing.title}}</a><div class="eyebrow">{{wing.symbol}} &nbsp; {{wing.title.toUpperCase()}}</div><h1>{{wing.headline}}</h1>@if(key==='blood'){<svg class="ecg" viewBox="0 0 400 42" aria-hidden="true"><path d="M0 21h115l10-10 12 20 12-28 16 37 13-19h222" fill="none" stroke="currentColor" stroke-width="2"/></svg>}<p>{{wing.description}}</p><div class="actions"><a class="button" [routerLink]="['/forms',wing.form]">{{wing.primary}} ↗</a>@if(wing.second){<a class="button secondary" [routerLink]="['/forms',wing.second]">{{wing.secondary}} ↗</a>}@else{<a class="text-link" routerLink="/impact">{{wing.secondary}} ↗</a>}</div></div></section>
<section class="wrap section">@if(key==='blood'){<div class="section-heading"><div><div class="eyebrow">A COMMUNITY READY TO CARE</div><h2>Find a donor connection.</h2></div><p>Contact details stay private.<br>Submit a blood request for coordination.</p></div><div class="filters"><select aria-label="Blood group" [(ngModel)]="group"><option value="">All blood groups</option>@for(g of groups;track g){<option>{{g}}</option>}</select><input aria-label="District" [(ngModel)]="district" placeholder="District"><input aria-label="City" [(ngModel)]="city" placeholder="City"><select aria-label="Availability" [(ngModel)]="availability"><option value="">All availability</option><option>Available</option><option>Temporarily Unavailable</option><option>Contact Before Request</option></select><button class="button" (click)="search()" [disabled]="busy">{{busy?'Searching…':'Search donors'}}</button></div>@if(error){<p class="error" role="alert">{{error}}</p>}@if(!donors.length){<div class="empty">{{searched?'No matching donors found. You can still submit a blood request.':'Choose your filters to explore the donor directory.'}}</div>}@else{<div class="stats">@for(d of donors;track $index){<div class="panel"><span class="pill">{{d.availability}}</span><h3>{{d.name}}</h3><p>{{d.bloodGroup}} · {{d.city}}</p><a routerLink="/forms/blood-request" class="text-link">Request a connection ↗</a></div>}</div>}}@else if(key==='hair'){<div class="eyebrow">FROM YOU, WITH LOVE</div><h2>A journey to confidence.</h2><div class="steps">@for(step of ['Grow Hair','Donate Hair','Hair Collection','Wig Creation','Restore Confidence'];track step;let i=$index){<span>{{i+1}}. {{step}} →</span>}</div><p>Register your interest before cutting or sending hair. The team will confirm current collection guidance and requirements with you.</p>}@else if(key==='medicine'){<div class="content-grid"><div><div class="eyebrow">CARE, WITH DIGNITY</div><h2>One less worry.<br>A little more hope.</h2><p>Tell us about the medicines you need and your hospital. Our volunteers review requests and coordinate available assistance.</p></div><div class="panel"><h3>Before you begin</h3><p>Have your medicine names, estimated cost and duration ready. Share only the information needed to review your request.</p></div></div>}@else{<div class="eyebrow">CELEBRATE WITH PURPOSE</div><h2>More meaning in every birthday.</h2><p>Choose the wing you care about and share your birthday giving interest. This pledge does not collect money or create a financial commitment.</p>}
</section>}@else{<section class="wrap section"><h1>Wing not found.</h1><a routerLink="/">Return home</a></section>}
`})export class Wing{api=inject(Api);route=inject(ActivatedRoute);key=this.route.snapshot.paramMap.get('wing')||'';wing=WINGS[this.key];groups=BLOOD_GROUPS;group='';district='';city='';availability='';donors:any[]=[];busy=false;error='';searched=false;async search(){this.busy=true;this.error='';try{this.donors=await this.api.call('donors',{filters:{bloodGroup:this.group,district:this.district,city:this.city,availability:this.availability}});this.searched=true}catch(e){this.error=(e as Error).message}finally{this.busy=false}}}
